### ISSUE TITLE
Music is the key

### ISSUE THREAD

**Issue by mdaehnert** [fanglingsu/nyancat-console#21]
Add Music to nyans journey.
Use one of these ideas:
- Beep
- ASCII bell \07
- a library like OpenAL

**Comment by fanglingsu** [comment]
Maybe libsdl could be also a possible candidate for the sound http://www.libsdl.org/.

**Comment by mdaehnert** [comment]
Cleaning up old own issues. If you feel like this one should not been closed, please let me know!
